# Generated by Django 3.1.7 on 2021-02-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistic_Counter',
            new_name='StatisticCounter',
        ),
    ]
